#!/bin/sh
#
# Spk-add - Install SliTaz packages. Read the README before adding or
# modifing any code in spk!
#
# Copyright (C) SliTaz GNU/Linux - BSD License
# Author: See AUTHORS files
#
. /usr/lib/slitaz/libspk.sh

#
# Functions
#

# Help and usage
usage() {
	name=$(basename $0)
	cat << EOT

$(boldify $(gettext "Usage:")) $name [packages|--options]

$(gettext "Install SliTaz Packages")

$(boldify $(gettext "Options:"))
  --forced    $(gettext "Force package reinstallation")
  --root=     $(gettext "Set the root file system path")
  --debug     $(gettext "Display some useful debug information")

$(boldify $(gettext "Examples:"))
  $name package1 package2 packageN

EOT
	exit 0
}

# Log install messages
# Parameters: package
log_install() {
	local pkg=$1
	debug "log_install: $logdir/$pkg/install.log"
	mkdir -p $logdir/$pkg
	tee $logdir/$pkg/install.log
}

# Update system databases
update_databases() {
	if [ -f $root/usr/bin/update-desktop-database ] && [ -n "$updatedesktopdb" ]; then
		chroot "$root/" /usr/bin/update-desktop-database /usr/share/applications 2>/dev/null
	fi
	# Mimetypes
	if [ -f $root/usr/bin/update-mime-database ] && [ -n "$updatemimedb" ]; then
		chroot "$root/" /usr/bin/update-mime-database /usr/share/mime
	fi
	# Icons
	if [ -f $root/usr/bin/gtk-update-icon-cache ] && [ -n "$updateicondb" ]; then
		chroot "$root/" /usr/bin/gtk-update-icon-cache /usr/share/icons/hicolor
	fi
	# Glib schemas
	if [ -f $root/usr/bin/glib-compile-schemas ] && [ -n "$compile_schemas" ]; then
		chroot "$root/" /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas
	fi
	# Kernel modules
	if [ -f $root/sbin/depmod ] && [ -n "$updatedepmod" ]; then
		chroot "$root/" /sbin/depmod -a
	fi
}

# This function installs a package in the rootfs.
# Parameters: package_name package_file
install_package() {
	local package_file=$1

	# Set by receipt: pre_depends() DEPENDS SELF_INSTALL CONFIG_FILES post_install()

	local package_name=$PACKAGE
	local package_dir="$installed/$package_name"
	mkdir -p $package_dir || exit 1

	# Run pre_depends from receipt if it exists
	if grep -q ^pre_depends $tmpdir/receipt; then
		pre_depends $root
	fi

	# Resolve package deps.
	if missing_deps $package_name $DEPENDS; then
		if [ "$confirm" ]; then
			gettext "Install missing dependencies"
			if ! confirm; then
				gettext "WARNING: Any dependencies installed"; newline
			fi
			install_deps $package_name $DEPENDS
		fi
	else
		newline
	fi

	boldify $(gettext "Adding"; echo " $package_name")
	separator
	gettext "Copying package..."
	cp $package_file $tmpdir && status
	cd $tmpdir

	# Add package checksum to $installed.$SUM
	if [ "$verbose" ]; then
		gettext "Incrementing:"; echo -n " $(basename $installed.$SUM)"
	fi
	sed -i "/  $PACKAGE-$VERSION*/"d $installed.$SUM 2>/dev/null
	$CHECKSUM $(basename $package_file) >> $installed.$SUM
	[ "$verbose" ] && status

	# Remove receipt that will be overwritten by extraction
	rm $tmpdir/receipt

	# Extract Package
	#debug "extract_package $package_file $tmpdir"
	extract_package $package_file $tmpdir

	# Handle cross compiled packages
	case "$SLITAZ_ARCH" in
		arm|x86_64) arch="-${SLITAZ_ARCH}" ;;
	esac
	tmpdir="$tmpdir/$PACKAGE-${VERSION}${arch}"

	# Get files to remove if upgrading
	local files_to_remove
	if [ -f $package_dir/files.list ]; then
		for file in $(cat $package_dir/files.list)
		do
			grep -q "^$(echo $file | grepesc)$" $tmpdir/files.list && continue
			local modifiers=$(cat $package_dir/modifiers 2> /dev/null; \
				fgrep -sl $package_dir */modifiers | cut -d/ -f1)
			for i in modifiers; do
				grep -qs "^$(echo $file | grepesc)$" $i/files.list && continue 2
			done
			files_to_remove="$files_to_remove $file"
		done
	fi
	debug "file_to_remove: $files_to_remove"

	# Create list of all possibly modified files
	local file_list
	for i in $(fgrep -v [ $tmpdir/files.list); do
		[ -e "${root}${i}" ] || continue
		[ -d "${root}${i}" ] && continue
		file_list="$file_list $i"
	done

	debug "file_list is set"

	# Check possibly modified files against other packages files.list
	debug "check modified files"
	for file in $file_list
	do
		local filegrep=$(egrep ^${file}$ $installed/*/files.list)
		if [ "$filegrep" ]; then
			local list=$(echo $filegrep | cut -d ":" -f 1)
			local count=0
			for pkg_file in $list; do
				local name=$(basename $(dirname $pkg_file))
				[  "$package_name" == "$name" ] && continue 2
				count=$(($count +1))
				[ "$count" == "1" ] && gettext "Modified package:"; \
					colorize 31 " $name"
				gettext "Overwriting file:"; echo " $file"
				# If confirm is set, ask to remove. Do we want that ?
				# If gawk is installed for example we will never remove Busybox
				# Use CONFLICTS receipt variable to avoid
				if [ "$confirm" ]; then
					echo -n "NOTE: confirm: spk-rm $name ???"; read
				fi
			done
		fi
	done

	cd $tmpdir || exit 1
	cp receipt files.list $package_dir || exit 1

	# Copy the description if found.
	[ -f "description.txt" ] && cp description.txt $package_dir

	# Pre install commands.
	if grep -q ^pre_install $package_dir/receipt; then
		pre_install $root
	fi

	# Handle Config Files from receipt
	if [ -n "$CONFIG_FILES" ]; then
		cd $fs || exit 1
		# save 'official' configuration files
		eval_gettext "Saving configuration files for \$package_name... "

		local confs
		for i in $CONFIG_FILES; do
			confs="$confs $(find ${i#/} -type f 2> /dev/null)"
		done

		echo $confs | cpio -o -H newc --quiet | gzip -9 > \
			$package_dir/volatile.cpio.gz

		# keep user configuration files
		for configfile in $confs; do
			[ -e $configfile ] || continue
			cp -a $configfile fs/$configfile
		done
		status
		cd - >/dev/null
	fi
	# Merge package FS with $root
	nb=$(cat files.list | wc -l)
	gettext "Installing files:"; echo -n " $nb"
	cp -a fs/* $root/
	status

	# Remove old config files
	if [ "$files_to_remove" ]; then
		gettext "Removing old files..."
		for file in $files_to_remove; do
			if [ "$verbose" ]; then
				gettext "Removing:"; echo " ${root}${file}"
			fi
			remove_with_path ${root}${file}
		done
		status
	fi
	cd - >/dev/null

	# Remove the temporary directory.
	if [ "$verbose" ]; then
		gettext "Removing all tmp files... "
		rm -rf $tmpdir && status
	else
		rm -rf $tmpdir
	fi

	# Post install commands.
	if grep -q ^post_install $package_dir/receipt; then
		post_install $root
	fi

 	# Update-desktop-database if needed.
	if [ "$(fgrep .desktop $package_dir/files.list | fgrep /usr/share/applications/)" ]; then
		updatedesktopdb=yes
	fi
	# Update-mime-database if needed.
	if [ "$(fgrep /usr/share/mime $package_dir/files.list)" ]; then
		updatemimedb=yes
	fi
	# Update-icon-database
	if [ "$(fgrep /usr/share/icon/hicolor $package_dir/files.list)" ]; then
		updateicondb=yes
	fi
	# Compile glib schemas if needed.
	if [ "$(fgrep /usr/share/glib-2.0/schemas $package_dir/files.list)" ]; then
		compile_schemas=yes
	fi
	# Update depmod list
	if [ "$(fgrep /lib/modules $package_dir/files.list)" ]; then
		updatedepmod=yes
	fi
	separator
	echo -n "$package_name ${VERSION}${EXTRAVERSION} "
	gettext "is installed"; newline
	newline
}

# Install .tazpkg packages.
# Parameters: package_file
install_local() {
	package_file="$1"
	#check_valid_tazpkg $package_file
	if [ -f "$package_file" ]; then
		if [ $(dirname $package_file) == "." ]; then
			package_file=$(pwd)/$package_file
		fi
		debug "package file: $package_file"
	else
		gettext "Unable to find:"; echo " $package_file"
		exit 1
	fi

	# Get package name now to check if installed
	mkdir -p $tmpdir
	extract_receipt $tmpdir $package_file
	source $tmpdir/receipt
	[ "$forced" ] || check_installed $PACKAGE
	[ "$count" == "1" ] && newline
	install_package $package_file
	update_databases
}

# Download and install a package. TODO: Handle Undigest Mirrors
# Parameters: package_name
install_web() {
	local package_name="$1"

	# Check if get-Package
	#if mirrored_pkg get-$package_name; then
		#package_name="get-$package_name"
		#exec=true
	#fi

	# Check if package is mirrored
	mirrored_pkg $package_name
	if [ ! "$mirrored" ]; then
		gettext "Could not find package on mirror:"
		boldify " $package_name" && exit 1
	fi

	# We want: package-version.tazpkg
	local package_full=$(full_package ${package_name})

	# Add architecture string to package full name
	case "$SLITAZ_ARCH" in
		arm|x86_64)
			pkgarch="-${SLITAZ_ARCH}.tazpkg"
			package_full=$(echo $package_full | sed s/.tazpkg/$pkgarch/) ;;
	esac

	# Let fetch the package by download()
	[ "$count" == 1 ] && newline
	debug "spk-add package: $package_name"
	download "$package_full" $mirror
	cd $CACHE_DIR

	# Create package path early to avoid dependencies loop
	mkdir -p $tmpdir
	extract_receipt $tmpdir "$CACHE_DIR/$package_full"
	source $tmpdir/receipt

	install_package "$CACHE_DIR/$package_full"

	#[ "$exec" ] && chroot $root/ $package_name
	[ "$exec" ] && $package_name $root
	update_databases
	unset_mirrored
}

# Install all missing deps of a package.
# Usage: install_deps package DEPENDS
install_deps() {
	local package=$1
	shift
	local deps="$@"
	for pkgorg in $deps; do
		local pkg=$(equivalent_pkg $pkgorg)
		# Check if package is not installed
		if [ ! -d "$installed/$pkg" ]; then
			if [ ! -f "$pkgsdesc" ]; then
				spk-up --list
			fi
			spk-add $pkg
		fi
	done
}

#
# Commands and exit
#

case "$1" in
	""|*usage|*help) usage ;;
esac

#
# Handle packages: package package.tazpkg ... packageN packageN.tazpkg
#

: ${count=0}
check_root

for pkg in $@
do
	case "$pkg" in
		*.tazpkg|*.spk)
			count=$(($count + 1))
			install_local $pkg | log_install $pkg;;
		*.deb|.rmp)
			echo "TODO: spk-convert then install" ;;
		*.*) gettext "WARNING: Not a valid package:"; echo " $pkg" ;;
		--*) continue ;;
		*)
			[ "$forced" ] || check_installed $pkg
			count=$(($count + 1))
			install_web $pkg | log_install $pkg;;
	esac
done

# Show all new counted packages in verbose mode
if [ "$verbose" ]; then
	gettext "Handled packages:"; colorize 34 " $count"
fi

exit 0
