#!/bin/sh
#
# Spk-Archive - SliTaz Package Archive Manager
#
#	NOT COMPLETE: Still need to re-write (just what was grabbed from tazpkg)
#
# Authors : See the AUTHORS files

source /usr/lib/slitaz/libspk.sh

usage() {
	name=$(basename $0)
	cat << EOT

$(boldify $(gettext "Usage:")) $name [command] package

$(boldify $(gettext "Commands:"))
  pack
  repack [--config]
  extract
  recompress

$(boldify "$(gettext "Example:")")
  $name extract package

EOT
	exit 0
}

# Extract a package with cpio and gzip/lzma to the current directory.
# Parameters: package_file
extract_package() {
	local package_file=$1
	local package_name=$(package_name $package_file)
	local size=$(du -sh $package_file | awk '{print $1}')
	gettext "Extracting"; echo -n " $package_name: $size"
	cpio -idm --quiet < ${package_file##*/} && rm -f ${package_file##*/}
	unlzma -c fs.cpio.lzma | cpio -idm --quiet && rm fs.cpio.lzma
	status
}

# Extract .tazpkg cpio archive into a directory.
# Parameters: package_file results_directory
extract() {
	local package_file=$1
	local target_dir=$2

	# Validate the file
	check_valid_tazpkg $package_file

	# Find the package name
	local package_name=$(package_name $package_file)

	# Create destination directory
	local dest_dir=$(pwd)/$package_name
	[ -n "$target_dir" ] && dest_dir=$target_dir/$package_name
	mkdir -p $dest_dir

	newline
	echo $(boldify $(gettext "Extracting:")) $package_name
	separator

	gettext "Copying original package..."
	cp $package_file $dest_dir
	status
	cd $dest_dir
	extract_package $package $package_file
	cd - > /dev/null
	separator
	echo -n "$package_name"
	gettext "is extracted to:"; echo " $dest_dir"
	newline
}

# Recompress .tazpkg cpio archive with lzma.
# Parameters: package_file
recompress() {
	local package_file=$1
	valid_tazpkg $package_file

	local package_name=$(package_name $package_file)

	newline
	echo $(boldify $(gettext "Recompressing:")) $package_name
	separator

	mkdir -p $TMP_DIR

	gettext "Copying original package..."
	cp $package_file $TMP_DIR
	status

	cd $TMP_DIR
	extract_package $package_file
	gettext "Recompressing the fs..."
	find fs | cpio -o -H newc --quiet | lzma e fs.cpio.lzma -si
	rm -rf fs
	status
	cd - > /dev/null

	gettext "Creating new package..."
	find $TMP_DIR -print | cpio -o -H newc --quiet > \
		$(basename $package_file).$$ && mv -f \
		$(basename $package_file).$$ \
		$(basename $package_file)
	status

	rm -rf $TMP_DIR
}

case $1 in
	extract|-e)
		extract_package $2 $3 ;;
	recompress|-r)
		recompress $2 ;;
	*)
		usage ;;
esac
